base_path: "src/main/resources"

preserve_hierarchy: true

files: [
  {
    source: "/assets/bettergrass/lang/en_us.json",
    translation: "/assets/bettergrass/lang/%locale_with_underscore%.json"
  }
]
